### ISSUE TITLE
A command of Firefox has changed.

### ISSUE THREAD

**Issue by h0cheung** [natask/firefox-tor-remap-C-n-and-C-p-for-search-bar-navigation#1]
In the latest version of Firefox (I use nightly), a command changed, so this patch should be modified as this:

```diff
--    <key id="printKb" data-l10n-id="print-shortcut" command="cmd_print"  modifiers="accel"/>
-+    <key id="printKb" data-l10n-id="print-shortcut" command="cmd_print"  modifiers="alt"/>
+-    <key id="printKb" data-l10n-id="print-shortcut" command="cmd_print_kb"  modifiers="accel"/>
++    <key id="printKb" data-l10n-id="print-shortcut" command="cmd_print_kb"  modifiers="alt"/>
```

Because there are several branches of Firefox, and I don't know whether other branches has this change, I didn't simply create a pull request.

By the way, is there any plan to add more Emacs style keybinding?

**Comment by natask** [comment]
Thanks for the diff. I had updated on my own machine but didn't upstream it.

I use firefox-developer arch exclusively so I am only going to maintain firefox versions that are in tandem with firefox-developer. A PR would have been welcome.

I don't plan to add more Emacs style keybinding. I use surfing keys and that is sufficient to give me all the keybindings I desire.
